### ISSUE TITLE
PSATD as Runtime Option

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#1187]
We want to redesign WarpX to use PSATD as a runtime option as soon as FFT support is compiled in. This will simplify WarpX by being able to build one WarpX binary that can be used with all MW solvers.

- [x] step 1: rename `algo.maxwell_fdtd_solver` to `algo.maxwell_solver` and throw warning if old option is still used: #1188
- [x] step 2: add `PSATD` to available options in `algo.maxwell_solver` and throw a clean runtime error if PSATD was selected but FFT libraries are not available: #1300
- [x] step 3: unify Travis runtime testing to always build against FFT libraries and picking PSATD as simple runtime options (we continue to ensure FFT libs are optional with other compile-time tests that are less costly) #1587

**Comment by ax3l** [comment]
This issue and the whole project on it is complete :rocket: :sparkles: 
https://github.com/ECP-WarpX/WarpX/projects/12
