### ISSUE TITLE
Overly long running physics tests

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#2630]
Let's reduce the runtime of these CI tests to speed up CI runs:
- [x] 80s: `averaged_galilean_3d_psatd` -> @oshapoval #2625
- [x] 80s: `comoving_2d_psatd_hybrid` -> @oshapoval -> add to #2625?
- [x] 83s: `galilean_2d_psatd_hybrid` -> @oshapoval -> add to #2625?
- [x] 80s: `multi_J_2d_psatd` -> @EZoni #2638 
- [x] 45s: `subcyclingMR` -> @EZoni #2632
- [ ] 336-370s: `particles_in_pml_3d_MR`
- [ ] 128s: `pml_psatd_dive_divb_cleaning`
- [ ] 168s: `multi_J_rz_psatd`

Goal: 2-20 sec are the usual runtimes :)

**Comment by EZoni** [comment]
I'll work on `multi_J_2d_psatd` because I need anyways to set up a similar test with PML boundary conditions instead of damped for #2603.

**Comment by ax3l** [comment]
Wuhu, thank you for the help @oshapoval @EZoni :tada:

**Comment by ax3l** [comment]
I saw in recent CI (#2556) that
- `averaged_galilean_3d_psatd` still runs around 45 seconds.
- `averaged_galilean_3d_psatd_hybrid` 69 seconds
- `galilean_3d_psatd` 71 seconds
- `galilean_3d_psatd_current_correction` 55 seconds

Do you think we can tune it slightly more?

I also noticed that these tests use 1 MPI rank and 1 OMP thread, we could use a `2` in _either_ `numprocs` or `numthreads`.

**Comment by EZoni** [comment]
We can probably use more than one core provided that we reduce the spectral order (otherwise the number of guard cells will become incompatible with the size of each subdomain, since the mesh is very coarse in these 3D tests). I will take a look at this.

**Comment by ax3l** [comment]
Found another few long runners:

## Cartesian 3D

### particles_in_pml_3d_MR
```
mpiexec -n 2 ./particles_in_pml_3d_MR.ex inputs_mr_3d  diag1.file_prefix=particles_in_pml_3d_MR_plt   amrex.abort_on_unused_inputs=1 amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1
   Execution time: 336.776 s
```

### pml_psatd_dive_divb_cleaning
```
mpiexec -n 2 ./pml_psatd_dive_divb_cleaning.ex inputs_3d  diag1.file_prefix=pml_psatd_dive_divb_cleaning_plt   amrex.abort_on_unused_inputs=1 amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1 warpx.do_similar_dm_pml = 0
   Execution time: 182.536 s
```

### RZ or NOMPI

### multi_J_rz_psatd
```
mpiexec -n 2 ./multi_J_rz_psatd.ex inputs_rz  diag1.file_prefix=multi_J_rz_psatd_plt   amrex.abort_on_unused_inputs=1 amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1 warpx.do_dynamic_scheduling=0 warpx.serialize_ics=1
   Execution time: 167.843 s
```

**Comment by ax3l** [comment]
X-ref: #2704 for the last long tests at the moment :)

Thank you @EZoni and @oshapoval :tada:
