### ISSUE TITLE
Add openPMD output for RZ geometry

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#353]
This is related to https://github.com/openPMD/openPMD-api/issues/545

## To Do

Meshes:
- [x] write Cartesian, reconstructed fields for theta=0 as in plotfiles: #1224
- [ ] in openPMD output:
  - do not write reconstructed at all
  - write all modes instead as defined by the standard

Particles:
- [x] fix theta mismatch after E/B were removed #1224
- position is stored internally for AMReX in r,z cylindrical + an extra theta component; we transform coords for push et al. on the fly
- momentum is stored already in Cartesian
- [x] for output, position & momentum shall be Cartesian, position still needs to be transformed #1225

**Comment by ax3l** [comment]
Just checked and added write examples to the API: https://openpmd-api.readthedocs.io/en/latest/usage/examples.html

I did a quick test based on 57cc9a3397f3e89e57b3bbc15ba8215ad2144b4f using the `Examples/Physics_applications/laser_acceleration/inputs_2d_rz` example.

I added the lines
```
diag1.format = openpmd
diag1.openpmd_backend = h5
```
for output.

From a quick `h5ls -r` it looks to me we are writing the reconstructed fields already, but not the individual modes. The field names are a bit all over the place, will take a look.

We fixed the particle positions a while back already to `r`, `z` naming. Should we also write the position `theta` maybe? Do we also want to transform momentum to `r`, `z` (, `theta`) in output? Or do we want all particle record components in Cartesian?

<details>
/                        Group
/data                    Group
/data/200                Group
/data/200/fields         Group
/data/200/fields/B       Group
/data/200/fields/B/z     Dataset {512, 64}
/data/200/fields/Bx      Dataset {512, 64}
/data/200/fields/By      Dataset {512, 64}
/data/200/fields/E       Group
/data/200/fields/E/z     Dataset {512, 64}
/data/200/fields/Ex      Dataset {512, 64}
/data/200/fields/Ey      Dataset {512, 64}
/data/200/fields/j       Group
/data/200/fields/j/z     Dataset {512, 64}
/data/200/fields/jx      Dataset {512, 64}
/data/200/fields/jy      Dataset {512, 64}
/data/200/fields/rho     Dataset {512, 64}
/data/200/particles      Group
/data/200/particles/beam Group
/data/200/particles/beam/E Group
/data/200/particles/beam/E/x Dataset {100}
/data/200/particles/beam/charge Group
/data/200/particles/beam/id Dataset {100}
/data/200/particles/beam/mass Group
/data/200/particles/beam/momentum Group
/data/200/particles/beam/momentum/x Dataset {100}
/data/200/particles/beam/momentum/y Dataset {100}
/data/200/particles/beam/momentum/z Dataset {100}
/data/200/particles/beam/position Group
/data/200/particles/beam/position/r Dataset {100}
/data/200/particles/beam/position/z Dataset {100}
/data/200/particles/beam/positionOffset Group
/data/200/particles/beam/positionOffset/r Group
/data/200/particles/beam/positionOffset/z Group
/data/200/particles/beam/weighting Dataset {100}
/data/200/particles/electrons Group
/data/200/particles/electrons/E Group
/data/200/particles/electrons/E/x Dataset {34228}
/data/200/particles/electrons/charge Group
/data/200/particles/electrons/id Dataset {34228}
/data/200/particles/electrons/mass Group
/data/200/particles/electrons/momentum Group
/data/200/particles/electrons/momentum/x Dataset {34228}
/data/200/particles/electrons/momentum/y Dataset {34228}
/data/200/particles/electrons/momentum/z Dataset {34228}
/data/200/particles/electrons/position Group
/data/200/particles/electrons/position/r Dataset {34228}
/data/200/particles/electrons/position/z Dataset {34228}
/data/200/particles/electrons/positionOffset Group
/data/200/particles/electrons/positionOffset/r Group
/data/200/particles/electrons/positionOffset/z Group
/data/200/particles/electrons/weighting Dataset {34228}
</details>

cc @RemiLehe @dpgrote

**Comment by ax3l** [comment]
I updated all details in the PR description :)

**Comment by ax3l** [comment]
@RemiLehe I think we are not yet writing individual modes of the field, are we?

**Comment by ax3l** [comment]
Implemented #2878
